### ISSUE TITLE
Webserver offline

### ISSUE THREAD

**Issue by koenBconnect** [INL/OpenConvert#5]
I have been trying to use this project for AI data science purposes. I am willing to use the openconvert.client.jar but it gives `java.net.UnknownHostException: svprre02`.

The service seems to be offline, or I'm doing something wrong.

Log: 
`java.net.UnknownHostException: svprre02
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:196)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:162)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394)
        at java.net.Socket.connect(Socket.java:606)
        at java.net.Socket.connect(Socket.java:555)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1240)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1167)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1061)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:995)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1354)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1329)
        at nl.inl.openconvert.web.util.MultipartFormDataClient.<init>(MultipartFormDataClient.java:59)
        at nl.inl.openconvert.client.OpenConvertClient.testTagger(OpenConvertClient.java:127)
        at nl.inl.openconvert.client.OpenConvertClient.main(OpenConvertClient.java:151)
usage: nl.inl.openconvert.client.OpenConvertClient <file to be tagged>`

Command being used:
`java -jar openconvert.client.jar -from txt -to TEI tekst.txt output.txt`

**Comment by JessedeDoes** [comment]
The default setting for server is a bit unfortunately set to an INT-internal address
Could you test something along the lines of
```
java -jar openconvert.client.jar -f text -t tei -a chn-tagger -s https://openconvert.ivdnt.org/openconvert/file test.txt
```

**Comment by koenBconnect** [comment]
That works! Cheers.
